from collections.abc import Callable


def heal(target: str, power: int) -> str:
    return f"you heal {target} with {power} power"


def attack(target: str, power: int) -> str:
    return f"you attack {target} with {power} power"


def spell_combiner(spell1: Callable, spell2: Callable) -> Callable:
    def super_spell(target: str, power: int) -> tuple[str, str]:
        result1 = spell1(target, power)
        result2 = spell2(target, power)
        return (result1, result2)
    return super_spell


def power_amplifier(base_spell: Callable, multiplier: int) -> Callable:
    def max_spell(target: str, power: int) -> str:
        new_power = power * multiplier
        return base_spell(target, new_power)
    return max_spell



def conditional_caster(condition: Callable, spell: Callable) -> Callable:
    pass


def spell_sequence(spells: list[Callable]) -> Callable:
    pass


def main() -> None:
    # Data generated by data_generator.py
    test_values = [13, 14, 17]
    test_targets = ['Dragon', 'Goblin', 'Wizard', 'Knight']

    print('0: spell combiner')
    print('1: power amplifier')
    choise = input('chose function:\n')

    match choise:
        case '0':
            print('== spell combiner ==')
            new_combine = spell_combiner(heal, attack)
            print(new_combine("Dragon", 17))
        case '1':
            print('== power amplifier ==')
            new_spell = power_amplifier(attack, 20)
            print(new_spell('dragon', 5))


if __name__ == "__main__":
    main()
